---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[cic_rabbitmq::packer]
    attributes:
