variable "aws_region" {}
variable "ami_id" {}
variable "instance_type" {}
variable "my_ip" {}
variable "public_key" {}
variable "acct_remote_state_bucket" {}
variable "acct_remote_state_key" {}
variable "network_remote_state_bucket" {}
variable "network_remote_state_key" {}